config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'about', to: 'pages#about', as: :about
  get 'transfer', to: 'pages#transfer', as: :transfer
  get 'pages/download', as: :download
  get 'contact', to: 'pages#contact', as: :contact
  post 'readers', to: 'readers#create'
  resources :orders, except: :index do
      get 'mailer', to: 'orders#mailer', as: :mailer
    resources :items, only: [:create, :destroy]
  end
  resources :donations
  resources :projects, except: [:destroy] do
    resources :volunteers, only: [:create]
  end
  resources :solicitations, only: :destroy
  get 'dashboard', to: 'users#dashboard_adm', as: :dashboard_adm
  get 'userdashboard', to: 'users#dashboard_user', as: :dashboard_user
  namespace :admin do
    resources :projects, except: [:index, :show]
    resources :volunteers, only: [:edit, :update, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  validates :email, :password, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def dashboard_adm
    @projects = Project.all
    @volunteers = Volunteer.all
    @donations = Donation.all
    @orders = Order.all
  end

  def dashboard_user
  end
end

app/views/users/dashboard_adm.html.erb
<div class="container">
  <div class="row">
    <div class="col my-5">
        <div class="tabs">
          <div class="tab-header">
            <div class="header active">
              <i class="fas fa-people-carry"></i> Items Doações
            </div>
            <div class="header">
              <i class="fas fa-hand-holding-heart"></i> Voluntários
            </div>
            <div class="header">
              <i class="fas fa-file-signature"></i> Projetos/Parcerias
            </div>
            <div class="header">
              <i class="fas fa-address-book"></i> Doações ofertadas
            </div>
          </div>
          <div class="tab-indicator"></div>
          <div class="tab-body">
            <div class="body active align-body">
              <section class="project-header">
                <h2>Items - Doações</h2>
                <%= link_to 'Inserir novo item', new_donation_path, class:"button-banner left-margin" %>
              </section>
              <section class="cem-width overflow-scroll">
                <table class="content-table">
                  <thead>
                    <tr>
                        <th>Produto</th>
                        <th>Quantidade e descrição</th>
                        <th>Categoria</th>
                        <th>Status</th>
                        <th> Editar/Excluir item </th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @donations.each do |donation|%>
                            <tr>
                                <td><%= donation.name %></td>
                                <td><%= "#{donation.quantity} #{donation.description}" %></td>
                                <td><%= donation.donation_tag %></td>
                                  <% if donation.status == true %>
                                    <td> Precisamos agora </td>
                                  <% else %>
                                    <td> Não Precisamos agora </td>
                                  <% end %>
                                <td  class="links-clean-green">
                                  <%= link_to edit_donation_path(donation) do %>
                                    <i class="far fa-edit"></i>
                                  <% end %>
                                  <%= link_to donation_path(donation), method: "delete" do %>
                                    <i class="far fa-trash-alt"></i>
                                  <% end %>
                                </td>
                            </tr>
                    <% end %>
                  </tbody>
                  </table>
              </section>
            </div>
            <div class="body align-body">
              <section class="project-header">
                <h2>Voluntários Casa Lar Emaús</h2>
              </section>
              <section class="cem-width overflow-scroll">
                <table class="content-table">
                  <thead>
                    <tr>
                      <th>Nome</th>
                      <th>Email</th>
                      <th>Contato</th>
                      <th>Disponibilidade</th>
                      <th>Natureza Jurídica</th>
                      <th> Editar/Excluir </th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @volunteers.each do |volunteer|%>
                      <tr>
                        <td><%= volunteer.name %></td>
                        <td><%= volunteer.email %></td>
                        <td><%= volunteer.phone %></td>
                        <td><%= volunteer.availability.capitalize %></td>
                        <td><%= volunteer.cpf_or_cnpj.upcase %></td>
                        <td class="links-clean-green" >
                          <%= link_to edit_admin_volunteer_path(volunteer) do %>
                            <i class="far fa-edit"></i>
                          <% end %>
                          <%= link_to admin_volunteer_path(volunteer), method: :delete do %>
                            <i class="far fa-trash-alt"></i>
                          <% end %>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </section>
            </div>
            <div class="body align-body">
              <section class="project-header">
                <h2> Projetos Casa Lar Emaús</h2>
                <%= link_to 'Criar um Projeto', new_admin_project_path, class:"button-banner left-margin" %>
              </section>
              <section class="wrapper">
                <% @projects.each do |project| %>
                  <%if project.photo.present? %>
                    <section class="item" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path project.photo.key %>')">
                  <% else %>
                    <section class="item default-image-project">
                  <% end %>
                      <h3><%= project.name%></h3>
                      <aside class="links-clean-white">
                        <%= link_to edit_admin_project_path(project) do %>
                          <i class="far fa-edit"></i>
                        <% end %>
                        <%= link_to admin_project_path(project), method: "delete" do %>
                          <i class="far fa-trash-alt"></i>
                        <% end %>
                      </aside>
                      <aside>
                        <% if project.status == true %>
                          <%= link_to "Ativo", edit_admin_project_path(project), class: "btn btn-success" %>
                        <% else %>
                          <%= link_to "Desativado", edit_admin_project_path(project), class: "btn btn-danger" %>
                        <% end %>
                      </aside>
                    </section>
                <% end %>
              </section>
            </div>
            <div class="body align-body">
              <section class="project-header">
                <h2> Dados sobre as doações ofertadas</h2>
              </section>
              <section class="cem-width overflow-scroll">
                <table class="content-table">
                  <thead>
                    <tr>
                      <th>Nome do doador</th>
                      <th>Email do doador</th>
                      <th>Telefone do doador</th>
                      <th>Itens oferecidos para doação</th>
                      <th> Excluir </th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @orders.each do |order|%>
                      <tr>
                        <td><%= order.name %></td>
                        <td><%= order.email %></td>
                        <td><%= order.phone %></td>
                        <td>
                          <% order.items.each do |item| %>
                          <%= "#{item.donation.name} - quantidade oferecida: #{item.quantity}" %>
                          <br>
                          <% end %>
                        </td>
                        <td class="links-clean-green" >
                          <%= link_to order_path(order), method: :delete do %>
                            <i class="far fa-trash-alt"></i>
                          <% end %>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </section>
            </div>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/users/dashboard_user.html.erb
<h1>Hi user</h1>