config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'about', to: 'pages#about', as: :about
  get 'transfer', to: 'pages#transfer', as: :transfer
  get 'pages/download', as: :download
  get 'contact', to: 'pages#contact', as: :contact
  post 'readers', to: 'readers#create'
  resources :orders, except: :index do
      get 'mailer', to: 'orders#mailer', as: :mailer
    resources :items, only: [:create, :destroy]
  end
  resources :donations
  resources :projects, except: [:destroy] do
    resources :volunteers, only: [:create]
  end
  resources :solicitations, only: :destroy
  get 'dashboard', to: 'users#dashboard_adm', as: :dashboard_adm
  get 'userdashboard', to: 'users#dashboard_user', as: :dashboard_user
  namespace :admin do
    resources :projects, except: [:index, :show]
    resources :volunteers, only: [:edit, :update, :destroy]
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer row">
  <div class="col-sm-12 col-md-4">
    <h2>Endereço:</h2>
    <p>Rua Eurico Hosterno, 321 - Santa Mônica. Florianópolis/SC - CEP: 88035-400</p>
    <h3>Contato:</h3>
    <p>Email: asm.casalaremaus@gmail.com. Fone: (48) 3233.4915</p>
  </div>

  <div class="links col-sm-12 col-md-4">
    <ul>
      <li><%= link_to "Doações", donations_path %></li>
      <li><%= link_to "Projetos", projects_path %></li>
      <li><%= link_to "Contato", contact_path %></li>
    </ul>
  </div>
  <div class="social-media col-sm-12 col-md-4">
    <ul>
      <li><i class="fab fa-instagram"></i></li>
      <li><i class="fab fa-facebook-f"></i></li>
      <li><i class="fab fa-twitter"></i></li>
    </ul>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
   <div class="nav-item dropdown nav-link" >
        <%= image_tag "logo.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdown">
          <% if user_signed_in? && current_user.admin == true %>
            <%= link_to "Painel de controle", dashboard_adm_path, class: "dropdown-item" %>
            <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          <% elsif user_signed_in? %>
            <%= link_to "Painel de controle", dashboard_user_path, class: "dropdown-item" %>
            <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          <% else %>
            <%= link_to "Entrar", new_user_session_path , class: "dropdown-item" %>
          <% end %>
        </div>
    </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link-black" %>
      </li>
      <li class="nav-item">
        <%= link_to "Projetos", projects_path, class: "nav-link-green" %>
      </li>
      <li class="nav-item">
        <%= link_to "Doações", donations_path, class: "nav-link-purple" %>
      </li>
      <li class="nav-item">
        <%= link_to "Contato", contact_path, class: "nav-link-red" %>
      </li>
    </ul>
  </div>
</div>