config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'about', to: 'pages#about', as: :about
  get 'transfer', to: 'pages#transfer', as: :transfer
  get 'pages/download', as: :download
  get 'contact', to: 'pages#contact', as: :contact
  post 'readers', to: 'readers#create'
  resources :orders, except: :index do
      get 'mailer', to: 'orders#mailer', as: :mailer
    resources :items, only: [:create, :destroy]
  end
  resources :donations
  resources :projects, except: [:destroy] do
    resources :volunteers, only: [:create]
  end
  resources :solicitations, only: :destroy
  get 'dashboard', to: 'users#dashboard_adm', as: :dashboard_adm
  get 'userdashboard', to: 'users#dashboard_user', as: :dashboard_user
  namespace :admin do
    resources :projects, except: [:index, :show]
    resources :volunteers, only: [:edit, :update, :destroy]
  end
end

app/views/pages/about.html.erb
<div class="container">
  <div class="row  my-5">
    <div class="col text-center">
        <h1>Bem vindos à Casa Lar Emaús</h1>
        <p>A Casa Lar é um abrigo para crianças entre 6 e 12 anos e fornece aos acolhidos moradia, alimentação, saúde, educação, lazer e outras atividades relacionadas com o desenvolvimento integral das crianças.</p>
    </div>
  </div>


  <div class="row mb-5">
    <div class="col-12 col-md-6">
      <div class="image-card green-card">
        <h2>Nosso Objetivo</h2>
      </div>
    </div>
     <div class="col-12 col-md-6 white-big-card">
      <p>O nosso objetivo é ser uma casa de acolhimento modelo para atendimento de crianças do sexo masculino com 06 até 12 anos, encaminhadas pelo Conselho Tutelar de Florianópolis, visando a permanência necessária e temporária, até reintrodução ao convívio familiar original, colocação em família substituta, adoção  (nacional ou internacional) ou preparação para vida autônoma, depois de completados 18 anos.</p>
    </div>
  </div>

  <div class="row mb-5">
    <div class="col-12 col-md-6 white-big-card">
      <p>Constituída como entidade privada sem finalidade lucrativa, com natureza filantrópica, a Casa Lar Emaus realiza o acolhimento previsto pela Lei n° 8.069/90, Estatuto da Criança e Adolescente (ECA), aplicado quando, após se esgotarem as demais medidas de proteção previstas,  torna-se meio para  proteger a criança ou adolescente das violações a que estejam sofrendo em sua família. A CasaLar Emaús busca oferecer às crianças um ambiente acolhedor e sadio com transmissão de valores essenciais ao seu bom desenvolvimento. Isso compreende aspectos básicos como moradia, alimentação, acesso à educação, saúde e também cultura, esporte, lazer e todo tipo de preocupação com seu bem estar,  oferecendo a  possibilidade de novas oportunidades e  buscando sempre sua formação integral.</p>
    </div>
    <div class="col-12 col-md-6">
      <div class="image-card pink-card">
        <h2>Nossa Base Jurídica</h2>
      </div>
    </div>
  </div>


  <div class="row mb-5">
    <div class="col-12 col-md-6">
      <div class="image-card blue-card">
        <h2>História</h2>
      </div>
    </div>
    <div class="col-12 col-md-6 white-big-card">
      <p>Durante o verão de 1993, jovens do Movimento de Emaús, movidos pelo espírito de serviço e com a convicção de que a “fé sem obras é morta”, iniciaram um trabalho de apoio a um grupo de crianças e adolescentes sem vínculo familiar no Município Rancho Queimado, a 75 km de Florianópolis (SC). Este trabalho, embora tenha findado pela dissolução da casa que acolhia tais crianças e adolescentes, motivou os jovens a  assumirem novos desafios na cidade de Florianópolis, dando origem à associação Ação Social Missão, em março do mesmo ano.</p>
    </div>
  </div>
  <div class="row mb-5">
    <div class="col-12 col-md-6 white-big-card">
      <p>Atualmente o vínculo de colaboradores envolvidos ocorre de duas formas distintas. Há uma equipe contratada e permanente para a realização de atividades essenciais: Psicóloga, Assistente Social e Cuidadores/Educadores, atuando de maneira profissional de acordo com sua especialidade. Todas as demais atividades são coordenadas e realizadas por voluntários, incluindo a diretoria da instituição (Diretoria geral, Diretoria financeira, Secretaria e Conselho).</p>
      <p>O sustento das suas atividades ocorre por meio de convênios com o Poder Público, convênios com pessoas jurídicas, e por meio de ações de arrecadação, eventos beneficentes e doações espontâneas.</p>
    </div>
    <div class="col-12 col-md-6">
      <div class="image-card green-card">
        <h2>Equipe</h2>
      </div>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="container">
  <div class="contact-container">
    <div class="map-div">
      <div id="map" style="width: 100%;height: 600px;box-shadow: 0px 5px 10px rgba(0, 0, 0, 0.1);" data-markers="<%= @marker.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
    <div class="contact-div col-4">
      <div class="form-volunteer-box">
        <h1>Fique por dentro das novidades</h1>
        <%= simple_form_for(@reader) do |f| %>
          <%= f.input :first_name, label: 'Nome:', placeholder: "Digite seu nome" %>
          <%= f.input :last_name, label: 'Sobrenome:', placeholder: "Digite seu sobrenome" %>
          <%= f.input :email, placeholder: "email@exemplo.com", label: "E-mail:" %>
          <%= f.button :submit, "Enviar", id: 'sweet-alert-news', class: 'button-donation-submit' %>
          <%= link_to "", root_path, id: "submit-link-news", class: "hidden" %>
        <% end %>
      </div>
      <hr>
      <div class="contact-info">
        <h2>Contato</h2>
        <ul>
          <li><a class="email" href="mailto:asm.casalaremaus@gmail.com" target="_blank"><i class="fas fa-envelope"></i></a></li>
          <li><a class="whatsapp" href="https://wa.me/+447507691336?text='Olá! Gostaria de mais informacoes sobre o projeto'"  target="_blank"><i class="fab fa-whatsapp"></i></a></li>
          <li><a class="phone" href=""><i class="fas fa-phone"  target="_blank"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" >
  <div class="banner-container">
    <div class="banner-text" >
      <h1>Casalar-Emaús</h1>
      <p>Mais que uma casa, um lar.</p>
      <%= link_to 'Conheça mais sobre o casa', about_path, class:'button-banner'%>
    </div>
  </div>
  <div class="image-crop">
    <%= image_tag "banner-green.png", alt: "Crianças dando as mãos", class: "banner-img"%>
  </div>
</div>

<div class="cards-container">
    <div class="row">
        <div class="col-sm-12 col-md-4 mrg">
          <div class="card-home blue-card">
          <%= image_tag "clipboard.svg", alt: "Projeto", class: "icon-card" %>
          <h2>Propostas</h2>
          <p>Quer propor uma parceria ou um novo projeto para a Casa Lar? Conte mais sobre sua ideia por aqui!</p>
          <%= link_to 'Tenho uma Proposta', new_project_path, class:'button-card'%>
        </div>
      </div>
      <div class="col-sm-12 col-md-4 mrg">
        <div class="card-home pink-card">
          <%= image_tag "box.svg", alt: "Caixa com coração", class: "icon-card"%>
          <h2>Doações</h2>
          <p>Você pode conferir as necessidades atuais da casa para contribuir com recursos e mantimentos.</p>
          <%= link_to 'Quero Doar', donations_path, class:'button-card' %>
        </div>
      </div>
      <div class="col-sm-12 col-md-4 mrg">
        <div class="card-home green-card">
          <%= image_tag "love.svg", alt: "Projeto", class: "icon-card" %>
          <h2>Voluntariado</h2>
          <p>A Casa Lar possui projetos em diferentes frentes para aqueles que desejam participar como voluntários.</p>
          <%= link_to 'Quero ser Voluntário', projects_path, class:'button-card' %>
        </div>
      </div>
  </div>
</div>

app/views/pages/transfer.html.erb
<div class="container">
  <div class="cards-container">
    <div class="row">
      <div class="col-sm-12 col-md-4 mrg">
        <div class="card-home blue-card">
          <%= image_tag "banco-do-brasil.svg", alt: "transferência", class: "bdb-icon" %>
          <span>Realize sua doação por depósito ou tranferência bancária</span>
          <%= image_tag "pix-test.png", alt: "código qr do pix", class: "pix-code" %>
          <div class="tranfer-card-text">
            <span>Depósito</span>
            <p>Agência: 5201-9</p>
            <p class="conta">Conta: 912.681-3</p>
          </div>
        </div>
      </div>
      <div class="col-sm-12 col-md-4 mrg">
        <div class="card-home pink-card">
          <%= image_tag "pagseguro.svg", alt: "pagseguro", class: "pg-icon" %>
          <span>Realize sua doação pelo cartão de crédito, via pagseguro</span>
          <a href="https://pag.ae/7Wbe1baQt" class="button-card">Cartão de crédito</a>
        </div>
      </div>
      <div class="col-sm-12 col-md-4 mrg">
        <div class="card-home green-card">
          <%= image_tag "ilumine-uma-vida.svg", alt: "ilumine uma vida", class: "iuv-icon" %>
          <span>Doe mensalmente através do débito na fatura de Energia Elétrica.</span>
          <%= link_to 'Baixe aqui', download_path, class:"button-card", target: :_blank %>
        </div>
      </div>
    </div>
  </div>
</div>