config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'about', to: 'pages#about', as: :about
  get 'transfer', to: 'pages#transfer', as: :transfer
  get 'pages/download', as: :download
  get 'contact', to: 'pages#contact', as: :contact
  post 'readers', to: 'readers#create'
  resources :orders, except: :index do
      get 'mailer', to: 'orders#mailer', as: :mailer
    resources :items, only: [:create, :destroy]
  end
  resources :donations
  resources :projects, except: [:destroy] do
    resources :volunteers, only: [:create]
  end
  resources :solicitations, only: :destroy
  get 'dashboard', to: 'users#dashboard_adm', as: :dashboard_adm
  get 'userdashboard', to: 'users#dashboard_user', as: :dashboard_user
  namespace :admin do
    resources :projects, except: [:index, :show]
    resources :volunteers, only: [:edit, :update, :destroy]
  end
end

app/models/donation.rb
class Donation < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, :quantity, :description, presence: true
  TAGS = ["Alimentos", "Higiene Pessoal", "Carnes", "Produtos de Limpeza", "Outro"]
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    @donations = Donation.all
    @donations = @donations.order("donation_tag")
  end

  def new
    @donation = Donation.new
  end

  def create
    @donation = Donation.new(donation_params)
    @donation.status = true
    if @donation.save
      redirect_to dashboard_adm_path
    else
      render 'new'
    end
  end

  def edit
    @donation = Donation.find(params[:id])
  end

  def update
    @donation = Donation.find(params[:id])
    if @donation.update(donation_params)
      redirect_to dashboard_adm_path
    else
      render 'edit'
    end
  end

  def destroy
    @donation = Donation.find(params[:id])
    @donation.destroy
    redirect_to dashboard_adm_path
  end

  private

  def donation_params
    params.require(:donation).permit(:name, :description, :status, :quantity, :donation_tag)
  end
end

app/views/donations/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-12 col-md-10">
      <div class="card-volunteer">
        <div class="row justify-content-center">
          <div class="col-sm-12 col-md-8">
            <div class="form-volunteer-box py-5">
              <%= simple_form_for @donation do |f| %>
                <%= f.input :name, label: 'Nome do item:', class: "form-group" %>
                <%= f.input :description, label: 'Descrição do item', class: "form-group" %>
                <%= f.input :quantity, label: 'Quantidade necessária', class: "form-group" %>
                <%= f.input :donation_tag, as: :select, collection: Donation::TAGS %>
                <%= f.input :status, label: 'Precisa agora desse item?', class: "form-group" %>
                <%= f.button :submit, "Confirmar alterações", class: "button-banner" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/donations/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-6 my-3 responsive-col" style="box-shadow: 0 0 15px rgb(0 0 0 / 20%);">
      <div class="py-5 text-center">
        <h1 class="mb-3">De que forma você prefere contribuir?</h1>
        <p> A Casa Lar Emaús posta mensalmente uma lista dos recursos materiais para a manutenção da casa, você pode conferir a lista abaixo e contribuir clicando no botão "Doar Mantimentos".</p>
      </div>
    </div>
    <div class="col-12 col-md-6 my-3 buttons-col">
      <%= link_to 'Doar mantimentos', new_order_path, class:'button-banner mb-3'%>
      <%= link_to 'Depositar valor', transfer_path, class:'button-banner'%>
    </div>
  </div>
  <div class="row">
    <div class="col" style="padding-left: 0;">
      <table class="content-table">
        <thead>
          <tr>
            <th>Produto</th>
            <th>Quantidade</th>
            <th>Categoria</th>
          </tr>
        </thead>
        <tbody>
          <% @donations.each do |donation|%>
            <% if donation.status != false && donation.quantity > 0 %>
              <% if donation.donation_tag == "Alimentos" %>
                <tr class="bg-gray">
                  <td><%= donation.name %></td>
                  <td><%= "#{donation.quantity} #{donation.description}" %></td>
                  <td><%= donation.donation_tag %></td>
                </tr>
              <% elsif donation.donation_tag == "Higiene Pessoal" %>
                <tr class="bg-gray">
                  <td><%= donation.name %></td>
                  <td><%= "#{donation.quantity} #{donation.description}" %></td>
                  <td><%= donation.donation_tag %></td>
                </tr>
              <% elsif donation.donation_tag == "Carnes" %>
                <tr class="bg-white">
                  <td><%= donation.name %></td>
                  <td><%= "#{donation.quantity} #{donation.description}" %></td>
                  <td><%= donation.donation_tag %></td>
                </tr>
              <% elsif donation.donation_tag == "Produtos de Limpeza" %>
                <tr class="bg-gray">
                  <td><%= donation.name %></td>
                  <td><%= "#{donation.quantity} #{donation.description}" %></td>
                  <td><%= donation.donation_tag %></td>
                </tr>
              <% else %>
                <tr class="bg-white">
                  <td><%= donation.name %></td>
                  <td><%= "#{donation.quantity} #{donation.description}" %></td>
                  <td><%= donation.donation_tag %></td>
                </tr>
              <% end %>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/donations/new.html.erb
<div class="container my-5">
  <div class="card-volunteer">
    <div class="row justify-content-center">
      <div class="col-sm-12 col-md-8">
        <br>
        <h2>Inserir um novo Item </h2>
        <br>
        <p>Preencha os campos abaixo para inserir um novo item para doação no website da Casa Lar Emaus</p>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-sm-12 col-md-8">
        <div class="form-volunteer-box py-5">
          <%= simple_form_for(@donation) do |f| %>
            <%= f.input :name, label: 'Qual o nome do novo item?', class: "form-group" %>
            <%= f.input :quantity, label: 'Qual a quantidade necessária?', class: "form-group" %>
            <%= f.input :description, label: 'Qual a unidade de medida (litros, unidades, etc) e descrição do item?', class: "form-group" %>
            <%= f.input :donation_tag, as: :select, collection: Donation::TAGS, label: "Qual a natureza desse item?" %>
            <%= f.input :status, label: 'Você precisa desse item esse mês?', class: "form-group" %>
            <%= f.button :submit, "Adicionar item", class: "button-banner" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>